export default {
	blue: {
		'uv-white-color': '#ffffff',
		'uv-gray-color': '#666666',
		'uv-lightgray-color': '#999999',
		'uv-red-color': '#F53F3F',

		'uv-main-color': '#000000',
		'uv-content-color': '#909193',
		'uv-text-color': '#1D2129',

		'uv-tips-color': '#909193',
		'uv-light-color': '#c0c4cc',
		'uv-border-color': '#dadbde',
		'uv-bg-color': '#f3f4f6',
		'uv-disabled-color': '#c8c9cc',

		'uv-primary': '#3D7EFF',
		'uv-primary-dark': '#3D7EFF',
		'uv-primary-disabled': '#9acafc',
		'uv-primary-light': '#E2ECFF',

		'uv-warning': '#f9ae3d',
		'uv-warning-dark': '#f1a532',
		'uv-warning-disabled': '#f9d39b',
		'uv-warning-light': '#fdf6ec',

		'uv-success': '#5ac725',
		'uv-success-dark': '#53c21d',
		'uv-success-disabled': '#a9e08f',
		'uv-success-light': '#f5fff0',

		'uv-error': '#f56c6c',
		'uv-error-dark': '#e45656',
		'uv-error-disabled': '#f7b2b2',
		'uv-error-light': '#fef0f0',

		'uv-info': '#909399',
		'uv-info-dark': '#767a82',
		'uv-info-disabled': '#c4c6c9',
		'uv-info-light': '#f4f4f5',
		'uv-info-bg': '#f5f5f7',
		'uv-App-theme': '#3D7EFF'
	},
	green: {
		'uv-white-color': '#ffffff',
		'uv-gray-color': '#666666',
		'uv-lightgray-color': '#999999',
		'uv-red-color': '#F53F3F',
		'uv-main-color': '#000000',
		'uv-content-color': '#909193',
		'uv-text-color': '#1D2129',

		'uv-tips-color': '#909193',
		'uv-light-color': '#c0c4cc',
		'uv-border-color': '#dadbde',
		'uv-bg-color': '#F5F6FA',
		'uv-disabled-color': '#c8c9cc',
		'uv-primary': '#27C1A5',
		'uv-primary-dark': '#27C1A5',
		'uv-primary-disabled': '#9acafc',
		'uv-primary-light': '#255aa61a',
		'uv-warning': '#f9ae3d',
		'uv-warning-dark': '#f1a532',
		'uv-warning-disabled': '#f9d39b',
		'uv-warning-light': '#fdf6ec',
		'uv-success': '#00B42A',
		'uv-success-dark': '#53c21d',
		'uv-success-disabled': '#a9e08f',
		'uv-success-light': '#EAFFEA',
		'uv-error': '#F53F3F',
		'uv-error-dark': '#e45656',
		'uv-error-disabled': '#FCECE8',
		'uv-error-light': '#FCECE8',
		'uv-info': '#909399',
		'uv-info-dark': '#767a82',
		'uv-info-disabled': '#c4c6c9',
		'uv-info-light': '#f4f4f5',
		'uv-info-bg': '#f5f5f7',
		'uv-App-theme': '#27C1A5',
		'uv-App-light-theme': '#E4F3F0',
		'uv-App-disable-theme': '#27C1A54D'
	},
	yellow: {
		'uv-white-color': '#ffffff',
		'uv-gray-color': '#666666',
		'uv-lightgray-color': '#999999',
		'uv-red-color': '#F53F3F',

		'uv-main-color': '#000000',
		'uv-content-color': '#909193',
		'uv-text-color': '#1D2129',

		'uv-tips-color': '#909193',
		'uv-light-color': '#c0c4cc',
		'uv-border-color': '#dadbde',
		'uv-bg-color': '#f3f4f6',
		'uv-disabled-color': '#c8c9cc',

		'uv-primary': '#FF7D00',
		'uv-primary-dark': '#FF7D00',
		'uv-primary-disabled': '#FFF7E8',
		'uv-primary-light': '#FFF7E8',

		'uv-warning': '#f9ae3d',
		'uv-warning-dark': '#f1a532',
		'uv-warning-disabled': '#f9d39b',
		'uv-warning-light': '#fdf6ec',

		'uv-success': '#5ac725',
		'uv-success-dark': '#53c21d',
		'uv-success-disabled': '#a9e08f',
		'uv-success-light': '#f5fff0',

		'uv-error': '#F53F3F',
		'uv-error-dark': '#F53F3F',
		'uv-error-disabled': '#f7b2b2',
		'uv-error-light': '#fef0f0',

		'uv-info': '#909399',
		'uv-info-dark': '#767a82',
		'uv-info-disabled': '#c4c6c9',
		'uv-info-light': '#f4f4f5',
		'uv-info-bg': '#f5f5f7',
		'uv-App-theme': '#f9ae3d'
	}
}
